#pragma once

#include "CoreMinimal.h"
#include "NativeGameplayTags.h"

namespace LevelWriterTags
{
	LEVELWRITER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_System);
	LEVELWRITER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Channel_Gameplay);

	LEVELWRITER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Start);
	LEVELWRITER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_End);
	LEVELWRITER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Door_Open);
	LEVELWRITER_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Event_Door_Close);
};